### ISSUE TITLE
Tasks in task list doesn't change on email change

### ISSUE THREAD

**Issue by bakribitar** [aicirt2012/icm-webclient#11]
Tasks in task list doesn't change on email change, sometimes it keeps the tasks from previous  email and adds the tasks from the current 
![task duplicates](https://user-images.githubusercontent.com/11980426/35537750-a57c4b1c-054b-11e8-8991-80744fbde7ea.PNG)

**Comment by sunborn23** [comment]
already fixed in current develop branch
